export default function Head() {
  return (
    <>
      <title>Sistem Mavoka</title>
      <meta name="description" content="Generated by Sistem Mavoka" />
      <link rel="icon" href="/public/img/logo-mavoka.png" /> {/* ganti dengan path logo kamu */}
    </>
  );
}
